"""add_pipeline_templates_schema_rules

Revision ID: 03ef5c23a239
Revises: 107f0859aeed
Create Date: 2026-06-09 10:59:28.759763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03ef5c23a239'
down_revision: Union[str, None] = '107f0859aeed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
