"""add_projects_and_providers

Revision ID: 7d6f598b22bd
Revises: 82b6d1fbf5d9
Create Date: 2026-06-06 11:58:13.376487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d6f598b22bd'
down_revision: Union[str, None] = '82b6d1fbf5d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
