"""add_projects_and_providers

Revision ID: 82b6d1fbf5d9
Revises: 7646ed13f110
Create Date: 2026-06-06 11:57:15.196497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82b6d1fbf5d9'
down_revision: Union[str, None] = '7646ed13f110'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datasets', sa.Column('project_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_datasets_project_id'), 'datasets', ['project_id'], unique=False)
    op.create_foreign_key(None, 'datasets', 'projects', ['project_id'], ['id'])
    op.drop_column('users', 'api_key_label')
    op.drop_column('users', 'encrypted_api_key')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('encrypted_api_key', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('api_key_label', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'datasets', type_='foreignkey')
    op.drop_index(op.f('ix_datasets_project_id'), table_name='datasets')
    op.drop_column('datasets', 'project_id')
    # ### end Alembic commands ###
