"""add_projects_providers

Revision ID: 9117e0285b2f
Revises: 7d6f598b22bd
Create Date: 2026-06-07 11:30:49.785117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9117e0285b2f'
down_revision: Union[str, None] = '7d6f598b22bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
